const firebaseConfig={databaseURL:"https://esh7nly-62354-default-rtdb.firebaseio.com/"};
if(!firebase.apps.length) firebase.initializeApp(firebaseConfig);
const db=firebase.database();
const cloudRef=db.ref("esh7nly");
const KEY="esh7nly_final_state";
const CLIENT_KEY="esh7nly_client_id";
const CLIENT_ID=localStorage.getItem(CLIENT_KEY)||(()=>{const x=(crypto&&crypto.randomUUID)?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);localStorage.setItem(CLIENT_KEY,x);return x})();
const defaultState={settings:{username:"admin",password:"1234",costs:{10:0,20:0,30:0,40:0,50:0,60:0,70:0},merchants:[{id:"abd",name:"عبد الحكيم",active:true},{id:"osama",name:"أسامة",active:true}],buyers:[{id:"owais",name:"عويس",active:true}],appearance:{brand:"ESH7NLY",tagline:"SMART TELECOM MANAGEMENT",primary:"#c62828",accent:"#2563eb",bg:"#f4f7fb",panel:"#ffffff",text:"#172033",backgroundImage:"",heroTitle:"أرقام أكثر، أرباح أكبر.",heroSubtitle:"إدارة أسرع. متابعة أدق. كل شغلك في لوحة واحدة."}},subscribers:[],activities:[],owaisPayments:[],_sync:{rev:0,updatedAt:0,updatedBy:"",settingsAt:0,deleted:[]}};
let state=loadState(),currentDay=11,currentMerchant="abd",selected=new Set(),pageHistory=[],dirtyThisSession=false,syncBusy=false,firebaseStarted=false,cloudHasData=false;
function loadState(){try{const x=JSON.parse(localStorage.getItem(KEY)||"{}");return normalizeState(x)}catch(e){return JSON.parse(JSON.stringify(defaultState))}}
function saveLocal(){localStorage.setItem(KEY,JSON.stringify(state))}
function money(n){return Number(n||0).toLocaleString("ar-EG")+" ج"}
function merchantName(v){const m=(state.settings.merchants||[]).find(x=>x.id===v);return m?.name||v||"غير محدد"}
function buyerName(v){const m=(state.settings.buyers||[]).find(x=>x.id===v);return m?.name||v||"غير محدد"}
function activeBuyers(){return (state.settings.buyers||[]).filter(m=>m.active!==false)}
function activeMerchants(){return (state.settings.merchants||[]).filter(m=>m.active!==false)}
function packageCost(p){return Number(state.settings.costs?.[p]||0)}
function todayISO(){return new Date().toISOString().slice(0,10)}
function nowMs(){return Date.now()}
function addLog(text){state.activities.unshift({id:uid(),text,time:new Date().toLocaleString("ar-EG"),updatedAt:nowMs(),updatedBy:CLIENT_ID});state.activities=state.activities.slice(0,100);touch();saveLocal();renderLog()}
function normalizeState(x){x=x||{};return {...defaultState,...x,settings:{...defaultState.settings,...(x.settings||{}),costs:{...defaultState.settings.costs,...((x.settings||{}).costs||{})},merchants:Array.isArray(x?.settings?.merchants)&&x.settings.merchants.length?x.settings.merchants:defaultState.settings.merchants,buyers:Array.isArray(x?.settings?.buyers)?x.settings.buyers:defaultState.settings.buyers,appearance:{...defaultState.settings.appearance,...((x.settings||{}).appearance||{})}},subscribers:Array.isArray(x.subscribers)?x.subscribers:[],activities:Array.isArray(x.activities)?x.activities:[],owaisPayments:Array.isArray(x.owaisPayments)?x.owaisPayments:[],_sync:{...defaultState._sync,...(x._sync||{}),deleted:Array.isArray(x?._sync?.deleted)?x._sync.deleted:[]}}}
function touch(){state._sync=state._sync||{};state._sync.updatedAt=nowMs();state._sync.updatedBy=CLIENT_ID}
state=normalizeState(state);
function applyAppearance(){const a=state.settings.appearance||defaultState.settings.appearance;const r=document.documentElement;r.style.setProperty("--primary",a.primary||"#c62828");r.style.setProperty("--accent",a.accent||"#2563eb");r.style.setProperty("--bg",a.bg||"#f4f7fb");r.style.setProperty("--panel",a.panel||"#ffffff");r.style.setProperty("--text",a.text||"#172033");document.title=(a.brand||"ESH7NLY")+" — نظام إدارة فودافون";document.querySelectorAll(".brand-text").forEach(e=>e.textContent=a.brand||"ESH7NLY");document.querySelectorAll(".brand-sub").forEach(e=>e.textContent=a.tagline||"SMART TELECOM MANAGEMENT");const body=document.body;body.style.backgroundImage=a.backgroundImage?`linear-gradient(#080b12cc,#080b12ee),url("${a.backgroundImage.replace(/"/g,"%22")}")`:"";body.style.backgroundSize=a.backgroundImage?"cover":"";body.style.backgroundAttachment=a.backgroundImage?"fixed":"";const heroTitle=document.querySelector("#homePage .hero-copy h1"),heroSub=document.querySelector("#homePage .hero-copy p");if(heroTitle)heroTitle.textContent=a.heroTitle||defaultState.settings.appearance.heroTitle;if(heroSub)heroSub.textContent=a.heroSubtitle||defaultState.settings.appearance.heroSubtitle;}
applyAppearance();
function setSync(t,kind="neutral"){const a=document.getElementById("syncMini"),b=document.getElementById("syncStatus");if(a){a.textContent=t;a.dataset.state=kind}if(b){b.textContent=t;b.dataset.state=kind}}
function hasLocalData(){return (state.subscribers?.length||0)||(state.activities?.length||0)||(state.owaisPayments?.length||0)||state._sync.updatedAt>0}
async function syncPush(){
  saveLocal();
  dirtyThisSession=true;
  if(!navigator.onLine||!firebaseStarted){setSync("🟡 محفوظ محليًا — في انتظار الاتصال","offline");return false}
  if(syncBusy)return false;
  syncBusy=true;
  setSync("جاري المزامنة…","busy");
  try{
    touch();
    await cloudRef.set(state);
    dirtyThisSession=false;
    cloudHasData=true;
    saveLocal();
    setSync("🟢 متزامن مع الأجهزة","online");
    return true;
  }catch(e){
    console.error("Firebase syncPush",e);
    setSync("🔴 فشل المزامنة — محفوظ محليًا","offline");
    saveLocal();
    return false;
  }finally{syncBusy=false}
}
function startFirebaseSync(){
  if(firebaseStarted)return;
  firebaseStarted=true;
  setSync("جاري الاتصال بـ Firebase…","busy");
  cloudRef.on("value",async snapshot=>{
    try{
      const remote=snapshot.val();
      if(remote){
        cloudHasData=true;
        const incoming=normalizeState(remote);
        if(!dirtyThisSession || Number(incoming._sync.updatedAt||0)>=Number(state._sync.updatedAt||0)){
          state=incoming;
          saveLocal();
          renderAll();
          dirtyThisSession=false;
        }
        setSync("🟢 متزامن مع الأجهزة","online");
      }else{
        cloudHasData=false;
        if(hasLocalData()){
          await syncPush();
        }else{
          setSync("🟢 Firebase جاهز — لا توجد بيانات","online");
        }
      }
    }catch(e){
      console.error("Firebase listener",e);
      setSync("🔴 خطأ في المزامنة","offline");
    }
  },error=>{
    console.error("Firebase listener error",error);
    setSync("🔴 Firebase رفض الاتصال — راجع Rules","offline");
  });
}
async function syncPull(show=true){
  if(show)setSync("جاري الاتصال بـ Firebase…","busy");
  if(!navigator.onLine){setSync("🟡 بدون إنترنت — الحفظ المحلي شغال","offline");return false}
  try{
    const snap=await cloudRef.once("value");
    const remote=snap.val();
    if(remote){state=normalizeState(remote);cloudHasData=true;saveLocal();renderAll();dirtyThisSession=false;setSync("🟢 متزامن مع الأجهزة","online");return true}
    if(hasLocalData())return await syncPush();
    setSync("🟢 Firebase جاهز — لا توجد بيانات","online");
    return true;
  }catch(e){console.error("Firebase syncPull",e);setSync("🔴 Firebase غير متاح — الحفظ المحلي شغال","offline");return false}
}
async function testSync(){setSync("جاري اختبار Firebase…","busy");const ok=await syncPull(true);if(ok)alert("تم الاتصال بـ Firebase بنجاح والمزامنة الفورية شغالة.");else alert("فشل الاتصال بـ Firebase. راجع Rules وتأكد أن القراءة والكتابة مسموحتان.")}
function isLogged(){return sessionStorage.getItem("esh7nly_logged")==="1"}
function login(){const u=document.getElementById("loginUser").value.trim(),p=document.getElementById("loginPass").value;if(u===state.settings.username&&p===state.settings.password){sessionStorage.setItem("esh7nly_logged","1");showApp();document.getElementById("loginMsg").textContent=""}else document.getElementById("loginMsg").textContent="اسم المستخدم أو كلمة المرور غير صحيحة"}
async function showApp(){document.getElementById("login").classList.add("hidden");document.getElementById("app").classList.remove("hidden");renderAll();startFirebaseSync();await syncPull(false)}
function currentPageId(){const p=[...document.querySelectorAll(".page")].find(x=>!x.classList.contains("hidden"));return p?.id||"homePage"}
function nav(id,remember=true){const cur=currentPageId();if(remember&&cur!==id)pageHistory.push(cur);document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));document.getElementById(id).classList.remove("hidden");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===id));updateBackButton();renderAll()}
function goBack(){const prev=pageHistory.pop();if(prev)nav(prev,false);else nav("homePage",false);updateBackButton()}
function updateBackButton(){const b=document.getElementById("backBtn");if(b)b.classList.toggle("back-hidden",pageHistory.length===0)}
function subscribers(){return state.subscribers||[]}
function dayStats(day){const a=subscribers().filter(s=>Number(s.day)===Number(day));const sales=a.reduce((x,s)=>x+Number(s.price||0),0);const cost=a.reduce((x,s)=>x+packageCost(s.package),0);const unpaidO=a.filter(s=>s.owais&&!s.paid).reduce((x,s)=>x+Number(s.price||0),0);return{all:a,sales,cost,profit:sales-cost,owaisDue:unpaidO}}
function totals(){const a=subscribers();const sales=a.reduce((x,s)=>x+Number(s.price||0),0),cost=a.reduce((x,s)=>x+packageCost(s.package),0);return{count:a.length,sales,cost,profit:sales-cost,owaisDue:a.filter(s=>s.owais&&!s.paid).reduce((x,s)=>x+Number(s.price||0),0),unpaid:a.filter(s=>!s.paid).reduce((x,s)=>x+Number(s.price||0),0)}}
function renderAll(){renderHome();renderSubscribers();renderMerchants();renderDashboard();renderLog()}
function renderHome(){const t=totals(),d11=dayStats(11),d26=dayStats(26);document.getElementById("homeStats").innerHTML=`<div class="stat"><span>إجمالي التفعيلات</span><b>${t.count}</b></div><div class="stat"><span>إجمالي المبيعات</span><b>${money(t.sales)}</b></div><div class="stat"><span>إجمالي الربح</span><b class="profit">${money(t.profit)}</b></div><div class="stat"><span>حساب عويس</span><b class="danger">${money(t.owaisDue)}</b></div>`;document.getElementById("dayProfitCards").innerHTML=[{d:11,s:d11},{d:26,s:d26}].map(x=>`<div class="stat"><span>تفعيلات يوم ${x.d}</span><b>${x.s.all.length}</b><div class="date-note">مبيعات ${money(x.s.sales)} · تكلفة ${money(x.s.cost)}</div><div class="profit">ربح ${money(x.s.profit)}</div></div>`).join("");const packageRows=[10,20,30,40,50,60,70].map(p=>({p,count:subscribers().filter(s=>Number(s.package)===p).length,profit:subscribers().filter(s=>Number(s.package)===p).reduce((x,s)=>x+Number(s.price||0)-packageCost(s.package),0)})).sort((a,b)=>b.profit-a.profit);const best=packageRows[0];const bestDay=d11.profit>=d26.profit?11:26;document.getElementById("smartStats").innerHTML=`<div class="smart-card"><span>أفضل باقة من حيث الربح</span><b>باقة ${best.p}</b><div class="date-note">${best.count} تفعيل · ربح ${money(best.profit)}</div></div><div class="smart-card"><span>أفضل يوم من حيث الربح</span><b>يوم ${bestDay}</b><div class="date-note">ربح ${money(bestDay===11?d11.profit:d26.profit)}</div></div>`;renderAlerts(false)}
function renewalClass(date){if(!date)return"green";const diff=Math.ceil((new Date(date+"T23:59:59")-new Date())/86400000);return diff<0?"red":diff<=2?"red":diff<=5?"yellow":"green"}
function renderAlerts(all=false){const arr=subscribers().filter(s=>s.dueDate).sort((a,b)=>String(a.dueDate).localeCompare(String(b.dueDate))).filter(s=>{const diff=Math.ceil((new Date(s.dueDate+"T23:59:59")-new Date())/86400000);return all||diff<=5}).slice(0,all?50:6);const box=document.getElementById("renewalAlerts");if(!arr.length){box.innerHTML='<div class="alert green">لا توجد تجديدات قريبة 🎉</div>';return}box.innerHTML=arr.map(s=>`<div class="alert ${renewalClass(s.dueDate)}"><div class="row"><div><b>${esc(s.name)}</b><div>${esc(s.number)} · ${merchantName(s.merchant)}</div><div class="date-note">الاستحقاق: ${s.dueDate}</div></div><div class="mini-actions"><button onclick="editSubscriber('${s.id}')">تعديل</button>${s.whatsapp?`<button class="whatsapp" onclick="window.open('${safeUrl(s.whatsapp)}','_blank')">واتساب</button>`:""}</div></div></div>`).join("")}
function renderSubscribers(){const mfEl=document.getElementById("merchantFilter");if(mfEl)mfEl.innerHTML=`<option value="all">كل الموردين</option>`+activeMerchants().map(m=>`<option value="${esc(m.id)}">${esc(m.name)}</option>`).join("");const bfEl=document.getElementById("buyerFilter");if(bfEl)bfEl.innerHTML=`<option value="all">كل التجار المشترين</option>`+activeBuyers().map(m=>`<option value="${esc(m.id)}">${esc(m.name)}</option>`).join("");const d=dayStats(currentDay),search=(document.getElementById("search")?.value||"").trim().toLowerCase(),status=document.getElementById("statusFilter")?.value||"all",mf=document.getElementById("merchantFilter")?.value||"all",pf=document.getElementById("packageFilter")?.value||"all",bf=document.getElementById("buyerFilter")?.value||"all";document.querySelectorAll(".day").forEach(b=>b.classList.toggle("active",Number(b.dataset.day)===currentDay));document.getElementById("subscriberSummary").innerHTML=`<div class="box"><span>العدد</span><b>${d.all.length}</b></div><div class="box"><span>المبيعات</span><b>${money(d.sales)}</b></div><div class="box"><span>التكلفة</span><b>${money(d.cost)}</b></div><div class="box"><span>الربح</span><b class="profit">${money(d.profit)}</b></div>`;const list=d.all.filter(s=>{const q=(s.name+" "+s.number+" "+(s.contact||"")).toLowerCase();return(!search||q.includes(search))&&(status==="all"||(status==="paid"?s.paid:!s.paid))&&(mf==="all"||s.merchant===mf)&&(pf==="all"||String(s.package)===pf)&&(bf==="all"||s.buyer===bf||(bf==="owais"&&s.owais))});document.getElementById("subscriberList").innerHTML=list.length?list.map(card).join(""):'<div class="alert">لا توجد نتائج.</div>'}
function card(s){const cost=packageCost(s.package),profit=Number(s.price||0)-cost;return `<div class="subscriber-card"><div class="row"><div><input type="checkbox" class="pick" data-id="${s.id}" ${selected.has(s.id)?"checked":""}> <b>${esc(s.name)}</b></div><span class="chip ${s.paid?"paid":"unpaid"}">${s.paid?"مسدد":"غير مسدد"}</span></div><div class="chips"><span class="chip">${esc(s.number)}</span><span class="chip">باقة ${s.package}</span><span class="chip">${merchantName(s.merchant)}</span>${s.buyer?`<span class="chip buyer-chip">${esc(buyerName(s.buyer))}</span>`:(s.owais?'<span class="chip buyer-chip">عويس</span>':"")}<span class="chip profit">ربح ${money(profit)}</span></div><div class="date-note">سعر البيع: ${money(s.price)} · التكلفة: ${money(cost)}${s.dueDate?" · الاستحقاق: "+s.dueDate:""}</div>${s.notes?`<div class="date-note">📝 ${esc(s.notes)}</div>`:""}<div class="card-actions"><button onclick="editSubscriber('${s.id}')">تعديل</button><button onclick="togglePaid('${s.id}')">${s.paid?"إلغاء التسديد":"تسديد"}</button><button class="copy-btn" onclick="copyNumber('${s.number}')">نسخ الرقم</button>${s.whatsapp?`<button class="whatsapp" onclick="window.open('${safeUrl(s.whatsapp)}','_blank')">واتساب</button>`:""}<button onclick="deleteSubscriber('${s.id}')">حذف</button></div></div>`}
function renderMerchants(){const ms=activeMerchants();if(!ms.some(m=>m.id===currentMerchant))currentMerchant=ms[0]?.id||"";const a=subscribers().filter(s=>s.merchant===currentMerchant),sales=a.reduce((x,s)=>x+Number(s.price||0),0),cost=a.reduce((x,s)=>x+packageCost(s.package),0);document.getElementById("merchantTabs").innerHTML=ms.map(m=>`<button class="merchant-tab ${m.id===currentMerchant?"active":""}" data-merchant="${esc(m.id)}">${esc(m.name)}</button>`).join("");document.getElementById("merchantSummary").innerHTML=`<div class="box"><span>الأرقام</span><b>${a.length}</b></div><div class="box"><span>المبيعات</span><b>${money(sales)}</b></div><div class="box"><span>التكلفة</span><b>${money(cost)}</b></div><div class="box"><span>الربح</span><b class="profit">${money(sales-cost)}</b></div>`;document.getElementById("merchantList").innerHTML=a.length?a.map(s=>`<div class="merchant-card"><div class="row"><b>${esc(s.name)}</b><span>${esc(s.number)}</span></div><div class="date-note">يوم ${s.day} · باقة ${s.package} · بيع ${money(s.price)} · تكلفة ${money(packageCost(s.package))} · <span class="profit">ربح ${money(Number(s.price)-packageCost(s.package))}</span></div></div>`).join(""):'<div class="alert">لا توجد أرقام لهذا التاجر.</div>'}
function renderDashboard(){const t=totals();const buyers=activeBuyers();const buyerDue=buyers.map(b=>{const rows=subscribers().filter(s=>(s.buyer===b.id)||(b.id==="owais"&&s.owais));return {b,rows,due:rows.filter(s=>!s.paid).reduce((x,s)=>x+Number(s.price||0),0),count:rows.length}});document.getElementById("reportStats").innerHTML=`<div class="stat"><span>المبيعات</span><b>${money(t.sales)}</b></div><div class="stat"><span>التكلفة</span><b>${money(t.cost)}</b></div><div class="stat"><span>الربح الصافي</span><b class="profit">${money(t.profit)}</b></div><div class="stat"><span>مستحقات التجار</span><b class="danger">${money(buyerDue.reduce((x,b)=>x+b.due,0))}</b></div>`;document.getElementById("costInputs").innerHTML=[10,20,30,40,50,60,70].map(p=>`<label>باقة ${p}<input data-cost="${p}" type="number" min="0" value="${packageCost(p)}"></label>`).join("");document.getElementById("settingUser").value=state.settings.username;document.getElementById("settingPass").value=state.settings.password;const d11=dayStats(11),d26=dayStats(26),all=t.owaisDue;document.getElementById("owaisAccount").innerHTML=`<div class="box"><span>يوم 11</span><b>${money(d11.owaisDue)}</b></div><div class="box"><span>يوم 26</span><b>${money(d26.owaisDue)}</b></div><div class="box"><span>الإجمالي</span><b class="danger">${money(all)}</b></div>`;renderMerchantManager();renderBuyerManager();renderAppearance();const buyerHtml=buyerDue.map(x=>`<div class="smart-card"><span>${esc(x.b.name)}</span><b>${money(x.due)}</b><div class="date-note">${x.count} تفعيل · ${x.due?"غير مسدد":"مسدد بالكامل"}</div></div>`).join("")||"<div class=\"muted\">لا يوجد تجار مشترون.</div>";const bd=document.getElementById("buyerSummary");if(bd)bd.innerHTML=buyerHtml;const bds=document.getElementById("buyerSummarySettings");if(bds)bds.innerHTML=buyerHtml}
function renderMerchantManager(){const el=document.getElementById("merchantManager");if(!el)return;el.innerHTML=activeMerchants().map(m=>{const count=subscribers().filter(s=>s.merchant===m.id).length;return `<div class="manager-row"><div><b>${esc(m.name)}</b><small>${count} رقم مرتبط</small></div><button class="danger-btn" onclick="removeMerchant('${esc(m.id)}')" ${count?"disabled":""}>حذف</button></div>`}).join("")||`<div class="muted">لا يوجد تجار.</div>`}
function renderAppearance(){const a=state.settings.appearance||defaultState.settings.appearance;const set=(id,v)=>{const e=document.getElementById(id);if(e)e.value=v??""};set("appearanceBrand",a.brand);set("appearanceTagline",a.tagline);set("appearancePrimary",a.primary);set("appearanceAccent",a.accent);set("appearanceBg",a.bg);set("appearancePanel",a.panel);set("appearanceText",a.text);set("appearanceImage",a.backgroundImage);set("appearanceHeroTitle",a.heroTitle);set("appearanceHeroSubtitle",a.heroSubtitle)}
function renderLog(){const el=document.getElementById("activityLog");if(el)el.innerHTML=(state.activities||[]).slice(0,40).map(x=>`<div class="log-item"><b>${esc(x.text)}</b><div class="date-note">${x.time}</div></div>`).join("")||'<div class="muted">لا توجد عمليات بعد.</div>'}
function openModal(id=null){const s=id?subscribers().find(x=>x.id===id):null;document.getElementById("modal").classList.remove("hidden");document.getElementById("modalTitle").textContent=s?"تعديل التفعيل":"تفعيل جديد";document.getElementById("editId").value=s?.id||"";document.getElementById("fName").value=s?.name||"";document.getElementById("fNumber").value=s?.number||"";document.getElementById("fContact").value=s?.contact||"";document.getElementById("fWhatsapp").value=s?.whatsapp||"";document.getElementById("fPackage").value=s?.package||"10";document.getElementById("fPrice").value=s?.price||"";document.getElementById("fPassword").value=s?.password||"";document.getElementById("fNotes").value=s?.notes||"";document.getElementById("fDueDate").value=s?.dueDate||"";document.getElementById("fMerchant").innerHTML=activeMerchants().map(m=>`<option value="${esc(m.id)}">${esc(m.name)}</option>`).join("");document.getElementById("fMerchant").value=s?.merchant||activeMerchants()[0]?.id||"";document.getElementById("fBuyer").innerHTML=`<option value="">لا يوجد / بيع مباشر</option>`+activeBuyers().map(m=>`<option value="${esc(m.id)}">${esc(m.name)}</option>`).join("");document.getElementById("fBuyer").value=s?.buyer||((s?.owais)?"owais":"");document.getElementById("fOwais").checked=!!s?.owais;checkCost()}
function closeModal(){document.getElementById("modal").classList.add("hidden")}
function editSubscriber(id){openModal(id)}
function uid(){return (crypto&&crypto.randomUUID)?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function saveSubscriber(e){e.preventDefault();const id=document.getElementById("editId").value||uid();const p=Number(document.getElementById("fPackage").value),price=Number(document.getElementById("fPrice").value||0),old=subscribers().find(s=>s.id===id);const s={id,name:document.getElementById("fName").value.trim(),number:document.getElementById("fNumber").value.trim(),contact:document.getElementById("fContact").value.trim(),whatsapp:document.getElementById("fWhatsapp").value.trim(),package:p,price,password:document.getElementById("fPassword").value,notes:document.getElementById("fNotes").value.trim(),dueDate:document.getElementById("fDueDate").value,merchant:document.getElementById("fMerchant").value,buyer:document.getElementById("fBuyer").value||"",owais:document.getElementById("fOwais").checked,day:old?.day||currentDay,paid:old?.paid||false,createdAt:old?.createdAt||new Date().toISOString(),updatedAt:nowMs(),updatedBy:CLIENT_ID};const duplicate=subscribers().some(x=>x.number===s.number&&x.id!==id&&Number(x.day)===s.day);if(duplicate&&!confirm("الرقم موجود بالفعل في نفس يوم التفعيل. هل تريد المتابعة؟"))return;if(price<packageCost(p)&&!confirm("سعر البيع أقل من التكلفة. هل تريد المتابعة؟"))return;const i=subscribers().findIndex(x=>x.id===id);if(i>=0)state.subscribers[i]=s;else state.subscribers.push(s);touch();addLog((old?"تعديل":"إضافة")+" المشترك "+s.name+" - "+s.number);closeModal();selected.delete(id);syncPush();renderAll()}
function togglePaid(id){const s=subscribers().find(x=>x.id===id);if(!s)return;s.paid=!s.paid;s.updatedAt=nowMs();s.updatedBy=CLIENT_ID;touch();addLog((s.paid?"تسديد ":"إلغاء تسديد ")+s.name);syncPush();renderAll()}
function deleteSubscriber(id){const s=subscribers().find(x=>x.id===id);if(!s)return;if(confirm("حذف المشترك؟")){state.subscribers=state.subscribers.filter(x=>x.id!==id);state._sync.deleted=[...(state._sync.deleted||[]),{id,at:nowMs()}].slice(-300);touch();addLog("حذف المشترك "+s.name);syncPush();renderAll()}}
function paySelected(){const ids=[...selected];if(!ids.length)return alert("حدد أرقام أولاً");ids.forEach(id=>{const s=subscribers().find(x=>x.id===id);if(s){s.paid=true;s.updatedAt=nowMs();s.updatedBy=CLIENT_ID}});touch();addLog("تسديد "+ids.length+" مشترك");selected.clear();syncPush();renderAll()}
function payOwais(){const a=dayStats(currentDay).all.filter(s=>s.owais&&!s.paid);if(!a.length)return alert("لا يوجد مبلغ مستحق لعويس في هذا اليوم");const total=a.reduce((x,s)=>x+Number(s.price||0),0);if(confirm("تسديد حساب عويس بمبلغ "+money(total)+"؟")){a.forEach(s=>{s.paid=true;s.updatedAt=nowMs();s.updatedBy=CLIENT_ID});state.owaisPayments.push({id:uid(),day:currentDay,amount:total,time:new Date().toISOString(),updatedAt:nowMs(),updatedBy:CLIENT_ID});touch();addLog("تسديد حساب عويس يوم "+currentDay+" بمبلغ "+money(total));syncPush();renderAll()}}
function payOwaisAll(){const a=subscribers().filter(s=>s.owais&&!s.paid);if(!a.length)return alert("لا يوجد حساب مستحق");const total=a.reduce((x,s)=>x+Number(s.price||0),0);if(confirm("تسديد كامل حساب عويس "+money(total)+"؟")){a.forEach(s=>{s.paid=true;s.updatedAt=nowMs();s.updatedBy=CLIENT_ID});state.owaisPayments.push({id:uid(),day:"all",amount:total,time:new Date().toISOString(),updatedAt:nowMs(),updatedBy:CLIENT_ID});touch();addLog("تسديد كامل حساب عويس "+money(total));syncPush();renderAll()}}
async function copyNumber(n){try{await navigator.clipboard.writeText(String(n));alert("تم نسخ الرقم")}catch(e){prompt("انسخ الرقم:",n)}}
function checkCost(){const p=Number(document.getElementById("fPackage").value),price=Number(document.getElementById("fPrice").value||0),box=document.getElementById("costWarning");if(price>0&&price<packageCost(p)){box.textContent="تنبيه: سعر البيع أقل من تكلفة الشراء ("+money(packageCost(p))+").";box.classList.remove("hidden")}else box.classList.add("hidden")}
function saveCosts(){state._sync.settingsAt=nowMs();touch();document.querySelectorAll("[data-cost]").forEach(i=>state.settings.costs[i.dataset.cost]=Number(i.value||0));addLog("تحديث تكاليف الباقات");syncPush();renderAll()}
function saveLogin(){state._sync.settingsAt=nowMs();touch();state.settings.username=document.getElementById("settingUser").value.trim()||"admin";state.settings.password=document.getElementById("settingPass").value||"1234";addLog("تحديث بيانات الدخول");syncPush();alert("تم حفظ بيانات الدخول ومزامنتها")}
function addMerchant(){const input=document.getElementById("newMerchantName");const name=input.value.trim();if(!name)return alert("اكتب اسم التاجر");const id="m_"+uid().replace(/[^a-zA-Z0-9_-]/g,"").slice(0,18);state.settings.merchants=[...(state.settings.merchants||[]),{id,name,active:true}];touch();addLog("إضافة التاجر "+name);input.value="";syncPush();renderAll();alert("تمت إضافة التاجر")}
function removeMerchant(id){const m=(state.settings.merchants||[]).find(x=>x.id===id);if(!m)return;if(subscribers().some(s=>s.merchant===id))return alert("لا يمكن حذف هذا التاجر لأنه مرتبط بأرقام. انقل الأرقام أولًا.");if(!confirm("حذف التاجر "+m.name+"؟"))return;state.settings.merchants=state.settings.merchants.filter(x=>x.id!==id);if(currentMerchant===id)currentMerchant=activeMerchants()[0]?.id||"";touch();addLog("حذف التاجر "+m.name);syncPush();renderAll()}
function renderBuyerManager(){const el=document.getElementById("buyerManager");if(!el)return;el.innerHTML=activeBuyers().map(m=>{const rows=subscribers().filter(s=>s.buyer===m.id||(m.id==="owais"&&s.owais));const due=rows.filter(s=>!s.paid).reduce((x,s)=>x+Number(s.price||0),0);return `<div class="manager-row"><div><b>${esc(m.name)}</b><small>${rows.length} تفعيل · مستحق ${money(due)}</small></div><button class="danger-btn" onclick="removeBuyer('${esc(m.id)}')" ${rows.length?"disabled":""}>حذف</button></div>`}).join("")||`<div class="muted">لا يوجد تجار مشترون.</div>`}
function addBuyer(){const input=document.getElementById("newBuyerName"),name=input.value.trim();if(!name)return alert("اكتب اسم التاجر الذي يشتري منك");const id="b_"+uid().replace(/[^a-zA-Z0-9_-]/g,"").slice(0,18);state.settings.buyers=[...(state.settings.buyers||[]),{id,name,active:true}];touch();addLog("إضافة تاجر مشتري "+name);input.value="";syncPush();renderAll();alert("تمت إضافة التاجر المشتري")}
function removeBuyer(id){const m=(state.settings.buyers||[]).find(x=>x.id===id);if(!m||id==="owais")return;if(subscribers().some(s=>s.buyer===id))return alert("لا يمكن حذف هذا التاجر لأنه مرتبط بتفعيلات. انقل التفعيلات أولًا.");if(!confirm("حذف التاجر المشتري "+m.name+"؟"))return;state.settings.buyers=state.settings.buyers.filter(x=>x.id!==id);touch();addLog("حذف تاجر مشتري "+m.name);syncPush();renderAll()}
function saveAppearance(){const a=state.settings.appearance||{};a.brand=document.getElementById("appearanceBrand").value.trim()||"ESH7NLY";a.tagline=document.getElementById("appearanceTagline").value.trim()||"SMART TELECOM MANAGEMENT";a.primary=document.getElementById("appearancePrimary").value||"#c62828";a.accent=document.getElementById("appearanceAccent").value||"#2563eb";a.bg=document.getElementById("appearanceBg").value||"#f4f7fb";a.panel=document.getElementById("appearancePanel").value||"#ffffff";a.text=document.getElementById("appearanceText").value||"#172033";a.backgroundImage=document.getElementById("appearanceImage").value.trim();a.heroTitle=document.getElementById("appearanceHeroTitle").value.trim();a.heroSubtitle=document.getElementById("appearanceHeroSubtitle").value.trim();state.settings.appearance=a;touch();addLog("تحديث هوية وتصميم الموقع");applyAppearance();syncPush();renderAll();alert("تم حفظ التصميم ومزامنته")}
function handleBackgroundUpload(e){const file=e.target.files?.[0];if(!file)return;if(file.size>4*1024*1024)return alert("اختار صورة أقل من 4 ميجابايت");const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const max=1800,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement("canvas");c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext("2d").drawImage(img,0,0,c.width,c.height);document.getElementById("appearanceImage").value=c.toDataURL("image/jpeg",.78);alert("تم تجهيز الخلفية. اضغط حفظ التصميم.")};img.src=r.result};r.readAsDataURL(file)}
function exportBackup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="esh7nly-backup-"+todayISO()+".json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function importBackup(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.subscribers||!x.settings)throw Error();state=normalizeState(x);state._sync.settingsAt=nowMs();touch();saveLocal();addLog("استيراد نسخة احتياطية");syncPush();renderAll();alert("تم الاستيراد")}catch(err){alert("ملف غير صالح")}};r.readAsText(f)}
function safeUrl(u){try{const x=new URL(u);return /^https?:$/.test(x.protocol)?x.href:"#"}catch(e){return"#"}}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
document.addEventListener("click",e=>{const p=e.target.closest("[data-page]");if(p)nav(p.dataset.page);if(e.target.matches(".day")){currentDay=Number(e.target.dataset.day);selected.clear();renderSubscribers()}if(e.target.matches(".merchant-tab")){currentMerchant=e.target.dataset.merchant;renderMerchants()}});
document.getElementById("backBtn").onclick=goBack;document.getElementById("homeBtn").onclick=()=>{pageHistory=[];nav("homePage",false)};document.getElementById("loginBtn").onclick=login;document.getElementById("loginPass").addEventListener("keydown",e=>{if(e.key==="Enter")login()});document.getElementById("logoutBtn").onclick=()=>{sessionStorage.removeItem("esh7nly_logged");location.reload()};document.getElementById("quickAdd").onclick=()=>openModal();document.getElementById("addSubscriberBtn").onclick=()=>openModal();document.getElementById("closeModal").onclick=closeModal;document.getElementById("modal").addEventListener("click",e=>{if(e.target.id==="modal")closeModal()});document.getElementById("subscriberForm").onsubmit=saveSubscriber;document.getElementById("fPackage").onchange=checkCost;document.getElementById("fPrice").oninput=checkCost;document.getElementById("paySelectedBtn").onclick=paySelected;document.getElementById("payOwaisBtn").onclick=payOwais;document.getElementById("payOwaisAllBtn").onclick=payOwaisAll;document.getElementById("saveCostsBtn").onclick=saveCosts;document.getElementById("saveLoginBtn").onclick=saveLogin;document.getElementById("addMerchantBtn")?.addEventListener("click",addMerchant);document.getElementById("addBuyerBtn")?.addEventListener("click",addBuyer);document.getElementById("saveAppearanceBtn")?.addEventListener("click",saveAppearance);document.getElementById("backgroundUpload")?.addEventListener("change",handleBackgroundUpload);document.getElementById("exportBtn").onclick=exportBackup;document.getElementById("importFile").onchange=importBackup;document.getElementById("forceSyncBtn").onclick=()=>{dirtyThisSession=true;syncPush()};document.getElementById("testSyncBtn")?.addEventListener("click",testSync);document.getElementById("showAlertsBtn").onclick=()=>{nav("homePage");renderAlerts(true)};["search","statusFilter","merchantFilter","buyerFilter","packageFilter"].forEach(id=>document.getElementById(id).addEventListener("input",renderSubscribers));document.getElementById("selectAllBtn").onclick=()=>{const boxes=[...document.querySelectorAll(".pick")];const allChecked=boxes.length&&boxes.every(c=>c.checked);boxes.forEach(c=>{c.checked=!allChecked;c.checked?selected.add(c.dataset.id):selected.delete(c.dataset.id)})};document.addEventListener("change",e=>{if(e.target.matches(".pick")){e.target.checked?selected.add(e.target.dataset.id):selected.delete(e.target.dataset.id)}});
if(isLogged())showApp();else document.getElementById("login").classList.remove("hidden");updateBackButton();document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!document.getElementById("modal").classList.contains("hidden"))closeModal()});

window.addEventListener("online",()=>{setSync("🟢 الإنترنت عاد — مزامنة تلقائية…","busy");if(dirtyThisSession)syncPush();else syncPull(false)});
window.addEventListener("offline",()=>setSync("🟡 بدون إنترنت — الحفظ المحلي شغال","offline"));
window.addEventListener("offline",()=>setSync("🟡 بدون إنترنت — الحفظ المحلي شغال","offline"));
